ingress:
  - hostname: jellyfin.justifhaive07.my.id
    service: http://192.168.1.101:8096
  - hostname: vault.justifhaive07.my.id
    service: https://192.168.1.104:8000
    originRequest:
      noTLSVerify: true
